---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
baseurl: 
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:              "City Evangelical Church"
keywords:           "City, evangelical, church, Leeds, best, christian, Jesus, bible, gospel, Christ, God, Faith, Lord"
description:        "We are a bible belieiving church in Beeston, Leeds who proclaim that Jesus is Lord, raised for the dead and the gospel is good news!"
source_link:        "https://github.com/cecleeds"
favicon:            "/img/favicon.ico"
favicon_16:         "/img/favicon-16x16.png"
favicon_32:         "/img/favicon-32x32.png"
touch_icon:         "/img/apple-touch-icon.png" ## City logo as apple touch icon
safari_pinned_tab:  "/img/safari-pinned-tab.svg" ## put safari pinned tab svg icon here

google_analytics_key: UA-175591016-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  white:        '#eaeaea'
  intro:        '#428bca'
  events:       '#ed7950'
  imnew:        '#66b266'
  aboutus:      '#5ea06e'
  sermons:      '#578e77'
  video:        '#4f7c80'
  thursday:     '#486a89'
  friday:       '#415992'
  saturday-two: '#39479b'
  contacts:     '#3035A4'
  black:        '#2e2e2e'
  ckyellow:     '#febd2e'
  ckblue:       '#01a8ff'
  ## white:      '#f8f8f8'
  blue:       '#002edf'
  green:      '#63bd2f'
  purple:     '#c869bf'
  orange:     '#fab125'
  turquoise:  '#0fbfcf'
  cityorange: '#f29526'
  cityblue:   '#009ddf'
  cyan:       '#00dfb2'
  red_orange: '#df4200'
  grey:       '#5e5e5e'
  blue1:      '#0065df'
  blue2:      '#002edf'
  blue3:      '#0a00df'
  bluepurple: '#4200df'
  citypurple: '#7a00df'

kramdown:
  auto_ids:  false

collections:
  kids:
    output: true
    permalink: /kids/

sass:
  sass_dir: stylesheets/_sass/
